"""empty message

Revision ID: 944d967bbc6e
Revises: fcb1fe23bd64
Create Date: 2024-09-18 23:48:22.451069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944d967bbc6e'
down_revision = 'fcb1fe23bd64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('availability')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
