"""empty message

Revision ID: c2bbc2775b63
Revises: f1d93e02e21e
Create Date: 2024-09-11 22:48:46.240823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2bbc2775b63'
down_revision = 'f1d93e02e21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=250), nullable=False))
        batch_op.drop_column('kind')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
