"""empty message

Revision ID: eefc9d638390
Revises: 669d12fe29f9
Create Date: 2024-09-16 16:01:32.224000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eefc9d638390'
down_revision = '669d12fe29f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
